# Generated by Django 2.1.7 on 2019-04-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMe', '0002_auto_20190413_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='cool_programmer.jpg', upload_to=''),
        ),
    ]
