# Generated by Django 2.1.7 on 2019-05-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMe', '0002_auto_20190508_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='type_vote',
            field=models.SmallIntegerField(choices=[(0, 'Dislike'), (1, 'Like')], verbose_name='Vote'),
        ),
    ]
