# Generated by Django 2.1.7 on 2019-04-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMe', '0004_auto_20190413_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
        ),
    ]
