# Generated by Django 2.1.7 on 2019-04-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMe', '0005_auto_20190413_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='answer',
            name='isRight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='images/cool_programmer.jpg', upload_to=''),
        ),
    ]
