# Generated by Django 2.1.7 on 2019-04-13 17:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('AskMe', '0006_auto_20190413_1924'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('list', django.db.models.manager.Manager()),
            ],
        ),
    ]
